apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-mysql-config
  labels:
    app: wordpress
    app.kubernetes.io/name: wordpress-mysql
data:
  primary.cnf: | #my.cnf 대체를 위한 설정 파일
    [mysqld]
    log-bin    
  replica.cnf: |
    [mysqld]
    super-read-only    
