apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql-read
  labels:
    app: wordpress
    app.kubernetes.io/name: wordpress-mysql
spec:
  selector:
    app: wordpress
    app.kubernetes.io/name: wordpress-mysql
  ports:
  - name: mysql
    port: 3306