apiVersion: storage.k8s.io/v1
kind: storageClass
metadata:
  name: gp3
  labels:
    app: wordpress
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
parameters:
  csi.storage.k8s.io/fstype: ext4
  type: gp3